#######################################
###                                 ###
### Author: Vital                   ###
### Date: February 22nd, 2024       ###
### Version: 1.0                    ###
###                                 ###
#######################################

/*
  * --- General Rules ---
  * Use underscore_names instead of CamelCase
  * Table names should be plural
  * Spell out id fields (item_id instead of id)
  * Don't use ambiguous column names
  * Name foreign key columns the same as the columns they refer to
  * Use caps for all SQL Queries
 */

CREATE SCHEMA IF NOT EXISTS billspace;

SET NAMES 'UTF8MB4';
SET TIME_ZONE = 'EU/Eastern';
USE billspace;


DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS
(
  ID               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME       VARCHAR(50) NOT NULL,
  LAST_NAME        VARCHAR(50) NOT NULL,
  EMAIL            VARCHAR(100) NOT NULL,
  PASSWORD         VARCHAR(100) DEFAULT NULL,
  ADDRESS          VARCHAR(255) DEFAULT NULL,
  PHONE            VARCHAR(20) DEFAULT NULL,
  TITLE            VARCHAR(50) DEFAULT NULL,
  BIO              VARCHAR(255) DEFAULT NULL,
  ENABLED          BOOLEAN DEFAULT FALSE,
  NON_LOCKED       BOOLEAN DEFAULT TRUE,
  USING_MFA        BOOLEAN DEFAULT FALSE,
  IMAGE_URL        VARCHAR(255) DEFAULT 'https://www.shutterstock.com/image-vector/blank-avatar-photo-place-holder-600nw-1114445501.jpg',
  CREATED_AT       DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT       UQ_USERS_EMAIL UNIQUE (EMAIL)
);


DROP TABLE IF EXISTS ROLES;
CREATE TABLE ROLES
(
    ID          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(50) NOT NULL UNIQUE,
    PERMISSIONS VARCHAR(255) NOT NULL,
    CONSTRAINT  UQ_ROLES_NAME UNIQUE (NAME)
);


DROP TABLE IF EXISTS UserRoles;
CREATE TABLE UserRoles
(
    ID         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID    BIGINT UNSIGNED NOT NULL,
    ROLE_ID    BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT  UQ_UserRoles_USER_ID UNIQUE (USER_ID)
);


DROP TABLE IF EXISTS EVENTS;
CREATE TABLE EVENTS
(
    ID          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TYPE        VARCHAR(50) NOT NULL CHECK ( TYPE IN ('LOGIN_ATTEMPT', 'LOGIN_ATTEMPT_FAILURE', 'LOGIN_ATTEMPT_SUCCESS', 'PROFILE_UPDATE', 'PROFILE_PICTURE_UPDATE', 'ROLE_UPDATE', 'PASSWORD_UPDATE', 'ACCOUNT_SETTINGS_UPDATE', 'MFA_UPDATE') ),
    DESCRIPTION VARCHAR(255) NOT NULL,
    CONSTRAINT  UQ_EVENTS_TYPE UNIQUE (TYPE)
);


DROP TABLE IF EXISTS UserEvents;
CREATE TABLE UserEvents
(
    ID         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID    BIGINT UNSIGNED NOT NULL,
    EVENT_ID   BIGINT UNSIGNED NOT NULL,
    DEVICE     VARCHAR(100) DEFAULT NULL,
    IP_ADDRESS VARCHAR(100) DEFAULT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);


DROP TABLE IF EXISTS AccountVerifications;
CREATE TABLE AccountVerifications
(
    ID          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID     BIGINT UNSIGNED NOT NULL,
    URL         VARCHAR(255) NOT NULL,
    expiration_date   DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT UQ_AccountVerifications_URL UNIQUE (URL),
    CONSTRAINT UQ_AccountVerifications_USER_ID UNIQUE (USER_ID)
);


DROP TABLE IF EXISTS ResetPasswordVerifications;
CREATE TABLE ResetPasswordVerifications
(
    ID               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID          BIGINT UNSIGNED NOT NULL,
    URL              VARCHAR(255) NOT NULL,
    expiration_date  DATETIME NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT UQ_ResetPasswordVerifications_URL UNIQUE (URL),
    CONSTRAINT UQ_ResetPasswordVerifications_USER_ID UNIQUE (USER_ID)
);


DROP TABLE IF EXISTS TwoFactorVerifications;
CREATE TABLE TwoFactorVerifications
(
    ID               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID          BIGINT UNSIGNED NOT NULL,
    CODE             VARCHAR(10) NOT NULL,
    expiration_date  DATETIME NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT UQ_TwoFactorVerifications_CODE UNIQUE (CODE),
    CONSTRAINT UQ_TwoFactorVerifications_USER_ID UNIQUE (USER_ID)
);



